export const hardSkillGroup: string;
export const hardSkillTitle: string;
export const lg: string;
export const skillItem: string;
export const skillsContainer: string;
export const skillsIcon: string;
export const skillsIcons: string;
export const softSkillItem: string;
export const tooltip: string;
